title: Home
description: "Wenlong Chen"
author:
  name: Wenlong Chen
  email: afterjourney1993@gmail.com
url: "https://fire337.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  footnote_backlink: "&#8617;"
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
